[package]
name = "tagmaster"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = {version = "0.13.1", features = ["tokio", "image"]}
iced_aw = { version = "0.12", features = ["card"] }

[profile.dev.package."*"]
opt-level = 3